name = "Co Pies Szczeka"
license = "MIT"
licenselink = "https://github.com/themefisher/tailbliss-hugo/blob/main/LICENSE"
description = "Profesjonalne szkolenie psów w przyjaznej atmosferze. Oferujemy zajęcia grupowe i indywidualne."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/themefisher/tailbliss-hugo"

# If you have a running demo of the theme.
demosite = "https://tailbliss.netlify.app/"

tags = ["blog", "portfolio"]
features = ["blog", "portfolio", "responsive", "seo-friendly", "fast"]

min_version = "0.41.0"

# If the theme has a single author
[author]
    name = "Co Pies Szczeka"
    homepage = "https://github.com/themefisher/tailbliss-hugo"

# If porting an existing theme
[original]
  name = "Hugo-Tailwind-3.1"
  author = "4044ever"
  homepage = "https://github.com/4044ever"
  repo = "https://github.com/4044ever/Hugo-Tailwind-3.1"